---
- become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: Install Node-Exporter
      community.docker.docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - 9100:9100
        restart_policy: unless-stopped
